################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 3.6
##  \   \         Application : 7 Series FPGAs Transceivers Wizard
##  /   /         Filename : gtx_test_exdes.xdc
## /___/   / ## \   \  / ##  \___\/\___ ##
##
## USER CONSTRAINTS FILE FOR MGT WRAPPER EXAMPLE DESIGN
## Generated by Xilinx 7 Series FPGAs Transceivers Wizard
##
## Device:  xc7k325t
## Package: ffg900
##
## (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
##
## This file contains confidential and proprietary information
## of Xilinx, Inc. and is protected under U.S. and
## international copyright and other intellectual property
## laws.
##
## DISCLAIMER
## This disclaimer is not a license and does not grant any
## rights to the materials distributed herewith. Except as
## otherwise provided in a valid license issued to you by
## Xilinx, and to the maximum extent permitted by applicable
## law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
## WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
## AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
## BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
## INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
## (2) Xilinx shall not be liable (whether in contract or tort,
## including negligence, or under any other theory of
## liability) for any loss or damage of any kind or nature
## related to, arising under or in connection with these
## materials, including for any direct, or any indirect,
## special, incidental, or consequential loss or damage
## (including loss of data, profits, goodwill, or any type of
## loss or damage suffered as a result of any action brought
## by a third party) even if such damage or loss was
## reasonably foreseeable or Xilinx had been advised of the
## possibility of the same.
##
## CRITICAL APPLICATIONS
## Xilinx products are not designed or intended to be fail-
## safe, or for use in any application requiring fail-safe
## performance, such as life-support or safety devices or
## systems, Class III medical devices, nuclear facilities,
## applications related to the deployment of airbags, or any
## other applications that could lead to death, personal
## injury, or severe property or environmental damage
## (individually and collectively, "Critical
## Applications"). Customer assumes the sole risk and
## liability of any use of Xilinx products in Critical
## Applications, subject only to applicable laws and
## regulations governing limitations on product liability.
##
## THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
## PART OF THIS FILE AT ALL TIMES.


################################## Clock Constraints ##########################


####################### GT reference clock constraints #########################


#create_clock -period 6.25 [get_ports Q3_CLK1_GTREFCLK_PAD_P_IN]





#create_clock -name drpclk_in_i -period 25 [get_ports DRP_CLK_IN_P]





# User Clock Constraints





#set_false_path -to [get_pins -hierarchical -filter {NAME =~ *_txfsmresetdone_r*/CLR}]
#set_false_path -to [get_pins -hierarchical -filter {NAME =~ *_txfsmresetdone_r*/D}]
#set_false_path -to [get_pins -hierarchical -filter {NAME =~ *_rxfsmresetdone_r*/CLR}]
#set_false_path -to [get_pins -hierarchical -filter {NAME =~ *_rxfsmresetdone_r*/D}]



####################### GT reference clock constraints #########################
create_clock -period 6.250 [get_ports GTP_CLK_p]

################################# RefClk Location constraints #####################
# 160 MHz MGT Ref. Clock from mSAS_FMC4S board
###X0Y8
#set_property LOC J7 [get_ports  GTP_CLK_n ]
#set_property LOC J8 [get_ports  GTP_CLK_p ]

#set_property LOC K5 [get_ports  serial_data_in_n ]
#set_property LOC K6 [get_ports  serial_data_in_p ]

####bank 118
### REF_CLK_1
set_property PACKAGE_PIN E8 [get_ports GTP_CLK_p]
set_property PACKAGE_PIN E7 [get_ports GTP_CLK_n]

###X0Y12
set_property PACKAGE_PIN E3 [get_ports serial_data_in_n_0]
set_property PACKAGE_PIN E4 [get_ports serial_data_in_p_0]
###X0Y13
set_property PACKAGE_PIN D5 [get_ports serial_data_in_n_1]
set_property PACKAGE_PIN D6 [get_ports serial_data_in_p_1]
###X0Y14
set_property PACKAGE_PIN B5 [get_ports serial_data_in_n_2]
set_property PACKAGE_PIN B6 [get_ports serial_data_in_p_2]
###X0Y15
set_property PACKAGE_PIN A8 [get_ports serial_data_in_p_3]
set_property PACKAGE_PIN A7 [get_ports serial_data_in_n_3]







################################# RefClk Location constraints #####################
#set_property LOC E7 [get_ports  Q3_CLK1_GTREFCLK_PAD_N_IN ]
#set_property LOC E8 [get_ports  Q3_CLK1_GTREFCLK_PAD_P_IN ]

## LOC constrain for DRP_CLK_P/N

## KC724 board constrain
# set_property LOC C25 [get_ports  DRP_CLK_IN_P]
# set_property LOC B25 [get_ports  DRP_CLK_IN_N]
## KC705 board constrain
#set_property LOC AD12 [get_ports  DRP_CLK_IN_P]
#set_property LOC AD11 [get_ports  DRP_CLK_IN_N]

################################# mgt wrapper constraints #####################
##---------- Set placement for gt0_gtx_wrapper_i/GTXE2_CHANNEL ------
#set_property LOC GTXE2_CHANNEL_X0Y12 [get_cells gtx_test_support_i/gtx_test_init_i/inst/gtx_test_i/gt0_gtx_test_i/gtxe2_i]
##---------- Set placement for gt1_gtx_wrapper_i/GTXE2_CHANNEL ------
#set_property LOC GTXE2_CHANNEL_X0Y13 [get_cells gtx_test_support_i/gtx_test_init_i/inst/gtx_test_i/gt1_gtx_test_i/gtxe2_i]
##---------- Set placement for gt2_gtx_wrapper_i/GTXE2_CHANNEL ------
#set_property LOC GTXE2_CHANNEL_X0Y14 [get_cells gtx_test_support_i/gtx_test_init_i/inst/gtx_test_i/gt2_gtx_test_i/gtxe2_i]
##---------- Set placement for gt3_gtx_wrapper_i/GTXE2_CHANNEL ------
#set_property LOC GTXE2_CHANNEL_X0Y15 [get_cells gtx_test_support_i/gtx_test_init_i/inst/gtx_test_i/gt3_gtx_test_i/gtxe2_i]

##---------- Set ASYNC_REG for flop which have async input ----------
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt0_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt0_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt1_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt1_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt2_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt2_frame_check*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt3_frame_gen*system_reset_r_reg}]
##set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt3_frame_check*system_reset_r_reg}]

##---------- Set False Path from one clock to other ----------


